<?php
$title = 'Add new user';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
if (!$this->form) {
    echo $this->error;
    //echo $flashMessages;
    return;
}
$form->setAttribute('action', $this->url('user', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('userId'));
echo $this->formRow($form->get('firstName'));
echo '<br>';
echo $this->formRow($form->get('lastName'));
echo '<br>';
echo $this->formRow($form->get('email'));
echo '<br>';
echo $this->formRow($form->get('password'));
echo '<br>';
echo $this->formRow($form->get('repassword'));
echo '<br>';
echo $this->formRow($form->get('role'));
echo '<br>';
echo $this->formRow($form->get('activated'));
echo '<br>';
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();