<?php
// module/Album/view/album/album/c.phtml:

$title = 'Change Password';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$user = $this->user;
$form->setAttribute('action', $this->url(
    'user',
    array(
        'action' => 'changePassword',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form),'<br/>';
echo $this->formHidden($form->get('userId')),'<br/>';
echo $this->formRow($form->get('oldPassword')),'<br/>';
echo $this->formRow($form->get('newPassword')),'<br/>';
echo $this->formRow($form->get('confirmNewPassword')),'<br/>';
echo $this->formSubmit($form->get('submit')),'<br/>';
echo $this->form()->closeTag(),'<br/>';

echo $this->error;

