<?php
$title = 'Delete user';
$this->headTitle($title);


?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php if ($this->error) {
    echo $this->error;
    return; 
} ?>
<p>Are you sure that you want to delete user 
    '<?php echo $this->escapeHtml($user->email); ?>'?
</p>
<?php

$url = $this->url('user', array(
    'action' => 'delete',
    'id' => $this->id,
        ));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $user->userId; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>