<?php
$title='User\'s detail';

$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
if (!$this->user) {
    echo $this->error;
    return;
}
echo "Full name: ",$this->escapeHtml($this->user->firstName),' ',$this->escapeHtml($this->user->lastName),'<br/>';
echo "Email: ", $this->escapeHtml($this->user->email),'<br/>';
echo "Role: ", $this->escapeHtml($this->user->role),'<br/>';
if ($this->escapeHtml($this->user->activated)) {
    echo 'Activated: This account has been activated','<br/>';
}
else {
    echo 'Activated: This account hasn\'t been activated or has been locked','<br/>';
}

echo '<a href=\'/zf2/qluser_zend/public/user\'>Follow this link to go back to the list page</a>';
