<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Edit User\'s Information';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
if (!$this->form) {
    echo $this->error;
} else {
    $form = $this->form;
    $user = $this->user;
    $form->setAttribute('action', $this->url(
        'user',
        array(
            'action' => 'edit',
            'id'     => $this->id,
        )
    ));
    $form->prepare();

    echo $this->form()->openTag($form),'<br/>';
    echo $this->formHidden($form->get('userId')),'<br/>';
    echo $this->formRow($form->get('firstName')),'<br/>';
    echo $this->formRow($form->get('lastName')),'<br/>';
    echo $this->formRow($form->get('email')),'<br/>';
    echo "<a href='/zf2/qluser_zend/public/user/changePassword/{$user->userId}'>Change password here</a><br/>";
    //echo $this->formHidden($form->get('password')),'<br/>';
    //echo $this->formHidden($form->get('repassword')),'<br/>';
    echo $this->formRow($form->get('role')),'<br/>';
    echo $this->formRow($form->get('activated')),'<br/>';
    echo $this->formSubmit($form->get('submit')),'<br/>';
    echo $this->form()->closeTag(),'<br/>';
}


//echo $user->firstName,' ',$user->lastName,' ',$user->userId,' ',$user->email,' ',$user->password,' ',$user->role,' ',$user->activated;
