<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <style>
            table, th, td {
                margin: auto;
                border: 1px solid black;
                border-collapse: collapse;
            }

            th, td {
                padding: 5px;
            }

            a {
                text-decoration: none;
            }

            .center {
                margin: auto;
                text-align: center;
            }
        </style>
    </head>
    <body>
        <?php        
        $title = 'Display Users Information';
        $this->headTitle($title);
        ?>
        <div class="center">
            <a href="<?php echo $this->url('user', array('action' => 'add')); ?>">Create new user</a> |
            Hello, <?php  echo $this->user->firstName. ' '. $this->user->lastName. ' | ' . $this->user->role;//echo $_SESSION['email'] . ' | ' . $_SESSION['role']; ?> |
            <a href="/zf2/qluser_zend/public/signin/logout">Log out</a> |
            <a href="<?php echo $this->url('user', array('action' => 'search')); ?>">Search for a user</a>
        </div>
        <br>
        <h1 class="center"><?php echo $this->escapeHtml($title); ?></h1>
        <br>
        <table>
            <tr>
                <th>No.</th>
                <th>First name</th>
                <th>Last name</th>
                <th>Email</th>
                <th>Role</th>
                <th>Activated</th>
                <?php
                    if ($this->user->role!='Operator') {
                    ?>
                <th>Edit</th>
                <th>Delete</th>
                    <?php } ?>
            </tr>
            <?php foreach ($this->paginator as $user): ?>
                <tr>
                    <td><?php echo $this->escapeHtml($user->userId); ?></td>
                    <td><a href="<?php echo '/zf2/qluser_zend/public/user/detail/'.$user->userId; ?>"><?php echo $this->escapeHtml($user->firstName); ?></a></td>
                    <td><?php echo $this->escapeHtml($user->lastName); ?></td>
                    <td><?php echo $this->escapeHtml($user->email); ?></td>
                    <td><?php echo $this->escapeHtml($user->role); ?></td>
                    <td>
                        <?php
                        if ($user->activated) {
                            echo 'Yes';
                        } else {
                            echo 'No';
                        }
                        ?>
                    </td>
                    <?php
                    if ($this->user->role!='Operator') {
                    ?>
                    <td><a href="<?php echo $this->url('user', array('action' => 'edit', 'id' => $user->userId));
                        ?>">Edit</a></td>
                    <td><a href="<?php echo $this->url('user', array('action' => 'delete', 'id' => $user->userId));
                        ?>">Delete</a></td></td>
                    <?php
                    }
                    ?>
                </tr>
            <?php endforeach; ?>
        </table>
        <div class="center">
            <?php
            echo $this->paginationControl(
                    $this->paginator, 
                    'sliding', 
                    'partial/paginator.phtml', 
                    array('route' => 'user')
                );
            ?>
        </div>
    </body>
</html>
